export const endpoints = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    changePassword: '/auth/change-password',
    connectPaypal: '/auth/connect-paypal',
  },
  users: {
    profile: (userId: number) => `/users/${userId}`,
    meProfile: '/users/me/profile',
    preferences: '/users/me/preferences',
    onlineStatus: '/users/me/online-status',
    pauseStatus: '/users/me/pause-status',
    deleteMe: '/users/me',
    visit: (userId: number) => `/users/${userId}/visit`,
  },
  discover: '/discover',
  likes: {
    root: '/likes',
    sent: '/likes/sent',
    stats: '/likes/stats',
    superlike: '/likes/superlike',
  },
  favorites: {
    root: '/favorites',
    status: (userId: number) => `/favorites/${userId}/status`,
    item: (userId: number) => `/favorites/${userId}`,
  },
  matches: {
    root: '/matches',
    startConversation: '/conversations/start',
    dateFeedback: (matchId: number) => `/matches/${matchId}/date-feedback`,
    item: (matchId: number) => `/matches/${matchId}`,
  },
  messages: {
    thread: (matchId: number) => `/messages/${matchId}`,
  },
  gifs: '/gifs',
  media: {
    upload: '/media/upload',
    mine: '/media',
    item: (mediaId: number) => `/media/${mediaId}`,
    user: (userId: number) => `/media/user/${userId}`,
    nudeStatus: (userId: number) => `/media/nude-status/${userId}`,
    unlockNude: (userId: number) => `/media/unlock-nude/${userId}`,
  },
  verification: {
    status: '/verification/status',
    submit: '/verification/submit',
  },
  premium: {
    status: '/premium/status',
    plans: '/premium/plans',
    creditPacks: '/premium/credit-packs',
    paypalConfig: '/premium/paypal-config',
    promoStatus: '/premium/promo-status',
  },
  payments: {
    createOrder: '/payments/paypal/create-order',
    captureOrder: '/payments/paypal/capture-order',
    history: '/payments/history',
  },
  blocks: {
    root: '/blocks',
    item: (userId: number) => `/blocks/${userId}`,
  },
  reports: {
    item: (userId: number) => `/reports/${userId}`,
  },
  notifications: {
    root: '/notifications',
    readAll: '/notifications/read-all',
    read: (id: number) => `/notifications/${id}/read`,
    thread: (id: number) => `/notifications/${id}/thread`,
    reply: (id: number) => `/notifications/${id}/reply`,
  },
  calls: {
    initiate: '/calls/initiate',
    incoming: '/calls/incoming',
    answer: (id: number) => `/calls/${id}/answer`,
    decline: (id: number) => `/calls/${id}/decline`,
    end: (id: number) => `/calls/${id}/end`,
    status: (id: number) => `/calls/${id}/status`,
    reoffer: (id: number) => `/calls/${id}/reoffer`,
    reanswer: (id: number) => `/calls/${id}/reanswer`,
    ice: (id: number) => `/calls/${id}/ice`,
  },
  guardian: {
    login: '/guardian/login',
    logout: '/guardian/logout',
    auth: '/guardian/auth',
    stats: '/guardian/stats',
    users: '/guardian/users',
    user: (id: number) => `/guardian/users/${id}`,
    userMedia: (id: number) => `/guardian/users/${id}/media`,
    ban: (id: number) => `/guardian/users/${id}/ban`,
    unban: (id: number) => `/guardian/users/${id}/unban`,
    grantPremium: (id: number) => `/guardian/users/${id}/grant-premium`,
    revokePremium: (id: number) => `/guardian/users/${id}/revoke-premium`,
    addCredits: (id: number) => `/guardian/users/${id}/add-credits`,
    reports: '/guardian/reports',
    report: (id: number) => `/guardian/reports/${id}`,
  },
} as const;
